### ISSUE TITLE
Maps don't work

### ISSUE THREAD

**Issue by eduardo2016xd** [Lunat1q/Catchem-PoGo#680]
Please update bot, maps don't work (Error 403)

**Comment by cheessyong** [comment]
Same problem here.

**Comment by fizzikzz** [comment]
Same issue here since this morning

**Comment by Igwa** [comment]
same issue here from about 2 hours

**Comment by teemo63** [comment]
hello I have the same problem that you have an idea of when is the bug will be fixed?

**Comment by LezardImperial** [comment]
Just wait for any answer from @Lunat1q and stop creating other issues threads. I'm sure it will be fixed soon just be patient. ;)

**Comment by impossibrubear** [comment]
There's already an issue thread opened. Use that one for discussing or keep playing normally, it should be working as it is reported by many people and me. It should be fixed soon.

**Comment by gamelordhacker** [comment]
[[IMG]http://i66.tinypic.com/2mdibl1.png[/IMG]](url)
[http://i66.tinypic.com/2mdibl1.png](url)

**Comment by gamelordhacker** [comment]
![111](https://cloud.githubusercontent.com/assets/21278539/18027781/91d9959c-6c9f-11e6-9e5c-835ed51c2480.png)

**Comment by eSPiYa** [comment]
It is related to the OpenstreetMap provider used by the GMap.NET.
Check line 74 of https://github.com/Lunat1q/Catchem-PoGo/blob/master/Catchem/Pages/MapPage.xaml.cs

I temporarily changed it to GoogleMap but I think this will still happen if there are lots of people requesting.

![Catch'em using Google Maps](http://i.imgur.com/XD66Obb.png)

**Comment by gamelordhacker** [comment]
how did you change it to google map?

**Comment by gdtesam** [comment]
we need to download source and compile ourselves after the change?

**Comment by Barusco** [comment]
@eSPiYa how did you changed?

**Comment by eSPiYa** [comment]
Through the code. Download it then compile.

**Comment by gamelordhacker** [comment]
TUT?

**Comment by eSPiYa** [comment]
@gamelordhacker 
It will take more time to download the tools you need than waiting for the actual fix.
But if you already have a Visual Studio 2015(or you may download Visual Studio 2015 Community Edition for free if you don't have it yet). Just clone the code, change the line you have to change, then run.

I'm not sure how to share my compile executable.

**Comment by Barusco** [comment]
@eSPiYa Change for the line for what?

the line is:  pokeMap.MapProvider = GMap.NET.MapProviders.GMapProviders.OpenStreetMap;
you changed for what?

**Comment by eSPiYa** [comment]
@Barusco 
pokeMap.MapProvider = GMap.NET.MapProviders.GMapProviders.**GoogleMap**;

**Comment by untesty** [comment]
and where do we put this file? In the directory?

**Comment by Barusco** [comment]
and how did you acess the file with the language code?
where is it?

**Comment by gdtesam** [comment]
its in the code before it becomes a .exe if you are really unsure i would just wait. i'm currently giving it a go anyway lol

**Comment by eSPiYa** [comment]
I'm trying to upload the compiled executable. This will only work on 1.6.5. Any malwares detected are not intended. Use it on your own risk(though I doubt my machine is infected by any malicious softwares or anything).

**Comment by eSPiYa** [comment]
[This is the GoogleMapped version of Catch'em for v1.4.6.5](https://drive.google.com/file/d/0B41ZnZXuOUNFWFVxNURrV3ZFY1k/view?usp=sharing). Use it at on your own risk. Just overwrite your executable with this file.

**Comment by Xx0jh0nny0xX** [comment]
Yeah! The maps don't work. Wee need to wait.

**Comment by untesty** [comment]
@eSPiYa Thank you :)

**Comment by eSPiYa** [comment]
@untesty 
You're welcome!

**Comment by gamelordhacker** [comment]
better i just wait .. i don't know CODES and compiling !! Thanks @ eSPiYa  

Bump Me for New Version or Fixed Map

**Comment by fizzikzz** [comment]
@eSPiYa Great on-the-fly support to tide things over until an official release! I was just about blow the dust off my VS2015 application and do my own alteration, but you got this out and uploaded before I got back to my comp from a coffee break!

**Comment by neo32330** [comment]
@eSPiYa It's working. Thank you :)

**Comment by JacksonTrue** [comment]
The same problem . It appeared after using Google key .
_______________________________________________________________________________
Та же самая проблема. Появилась после использования гугл ключа.
http://screenshot.ru/233ab821cf37e6ce4c2a043442f99d6f

**Comment by eSPiYa** [comment]
I forgot to change the WorldMap but who's using that?

**Comment by gamelordhacker** [comment]
eSPiYa commented 17 minutes ago
This is the GoogleMapped version of Catch'em for v1.4.6.5. Use it at on your own risk. Just overwrite your executable with this file.

Ohhh!!! Thanks You for this...

**Comment by viniciusduzzi** [comment]
same

**Comment by viniciusduzzi** [comment]
same problem in last version

**Comment by eSPiYa** [comment]
@viniciusduzzi 
You may try [my fix](https://github.com/Lunat1q/Catchem-PoGo/issues/680#issuecomment-242919505) while waiting for the official fix.

**Comment by Bay101** [comment]
Fixed, will be in next release :smiley:

**Comment by eduardo2016xd** [comment]
Bay101, when upload next release? :(

**Comment by madafoquer** [comment]
Thank you @eSPiYa (:

**Comment by Lunat1q** [comment]
1 row of code should be changed, I'll release it as soon as I get back home
